repo: https://curl.se/download/curl-8.5.0.zip
ver: 8.5.0
tag_prefix: curl-
tag_dot2ul: true
cb_tool: cmake
config_options_unix: -DCURL_DISABLE_LDAP=TRUE -DCURL_USE_LIBSSH2=FALSE -DBUILD_CURL_EXE=FALSE -DCURL_DISABLE_TESTS=TRUE -DCURL_USE_OPENSSL=TRUE -DBUILD_SHARED_LIBS=OFF
config_options_embed: ''
config_options_msw: -DCURL_DISABLE_LDAP=TRUE -DCURL_USE_LIBSSH2=FALSE -DBUILD_CURL_EXE=FALSE -DCURL_DISABLE_TESTS=TRUE -DCURL_USE_OPENSSL=TRUE -DBUILD_SHARED_LIBS=ON
config_options_uwp: -DCURL_DISABLE_LDAP=TRUE
